# Generated by Django 4.2.23 on 2025-06-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('restaurant', '음식점'), ('cafe', '카페/디저트')], max_length=20, verbose_name='카테고리')),
                ('subcategory', models.CharField(blank=True, choices=[('korean', '한식'), ('snack', '분식'), ('japanese', '일식'), ('fastfood', '패스트푸드'), ('salad', '샐러드')], max_length=20, null=True, verbose_name='음식 종류')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='store_photo', verbose_name='가게 이미지')),
                ('name', models.CharField(max_length=100, verbose_name='가게 이름')),
                ('rating', models.FloatField(default=0.0, verbose_name='별점')),
                ('address', models.CharField(max_length=200, verbose_name='주소')),
                ('latitude', models.FloatField(verbose_name='위도')),
                ('longitude', models.FloatField(verbose_name='경도')),
                ('congestion', models.CharField(choices=[('low', '여유'), ('medium', '보통'), ('high', '혼잡')], default='low', max_length=10, verbose_name='혼잡도')),
                ('current_customers', models.IntegerField(default=0, verbose_name='현재 손님 수')),
                ('max_customers', models.IntegerField(default=0, verbose_name='최대 수용 인원')),
                ('is_open', models.BooleanField(default=True, verbose_name='영업 여부')),
                ('is_breaktime', models.BooleanField(default=False, verbose_name='브레이크 타임 여부')),
                ('naver_url', models.URLField(blank=True, null=True, verbose_name='가게 네이버 링크')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
        ),
    ]
