# Generated by Django 4.2.23 on 2025-06-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='is_breaktime',
        ),
        migrations.RemoveField(
            model_name='store',
            name='is_open',
        ),
        migrations.AddField(
            model_name='store',
            name='break_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='break_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
