# Generated by Django 4.2.23 on 2025-06-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_remove_store_is_breaktime_remove_store_is_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='break_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='브레이크타임 종료 시간'),
        ),
        migrations.AlterField(
            model_name='store',
            name='break_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='브레이크타임 시작 시간'),
        ),
        migrations.AlterField(
            model_name='store',
            name='close_time',
            field=models.TimeField(blank=True, null=True, verbose_name='영업 종료 시간'),
        ),
        migrations.AlterField(
            model_name='store',
            name='open_time',
            field=models.TimeField(blank=True, null=True, verbose_name='영업 시작 시간'),
        ),
    ]
