# Generated by Django 4.2.23 on 2025-06-29 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0004_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_count', models.PositiveIntegerField(choices=[(1, '1명'), (2, '2명'), (3, '3명'), (4, '4명'), (5, '5명'), (6, '6명 이상')])),
                ('wait_time', models.CharField(choices=[('바로 입장', '바로 입장'), ('10분 이내', '10분 이내'), ('20분 이내', '20분 이내'), ('30분 이내', '30분 이내'), ('1시간 이내', '1시간 이내'), ('2시간 이상', '2시간 이상')], max_length=20)),
                ('congestion', models.CharField(choices=[('여유', '여유'), ('보통', '보통'), ('혼잡', '혼잡')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_logs', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
